services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_URL=postgresql://user:pass@db:5432/resume_db
    volumes:
      - .:/var/www/html
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=resume_db
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
